/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package OSPIcecap.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the DataEntry service. Represents a row in the &quot;icecap_DataEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link OSPIcecap.model.impl.DataEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OSPIcecap.model.impl.DataEntryImpl}.
 * </p>
 *
 * @author Jerry H. Seo
 * @see DataEntry
 * @see OSPIcecap.model.impl.DataEntryImpl
 * @see OSPIcecap.model.impl.DataEntryModelImpl
 * @generated
 */
@ProviderType
public interface DataEntryModel extends BaseModel<DataEntry>, LocalizedModel,
	ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data entry model instance should use the {@link DataEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this data entry.
	 *
	 * @return the primary key of this data entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this data entry.
	 *
	 * @param primaryKey the primary key of this data entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry ID of this data entry.
	 *
	 * @return the entry ID of this data entry
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this data entry.
	 *
	 * @param entryId the entry ID of this data entry
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the collection ID of this data entry.
	 *
	 * @return the collection ID of this data entry
	 */
	public long getCollectionId();

	/**
	 * Sets the collection ID of this data entry.
	 *
	 * @param collectionId the collection ID of this data entry
	 */
	public void setCollectionId(long collectionId);

	/**
	 * Returns the group ID of this data entry.
	 *
	 * @return the group ID of this data entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this data entry.
	 *
	 * @param groupId the group ID of this data entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this data entry.
	 *
	 * @return the company ID of this data entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this data entry.
	 *
	 * @param companyId the company ID of this data entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this data entry.
	 *
	 * @return the user ID of this data entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this data entry.
	 *
	 * @param userId the user ID of this data entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this data entry.
	 *
	 * @return the user uuid of this data entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this data entry.
	 *
	 * @param userUuid the user uuid of this data entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this data entry.
	 *
	 * @return the create date of this data entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this data entry.
	 *
	 * @param createDate the create date of this data entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the comments of this data entry.
	 *
	 * @return the comments of this data entry
	 */
	public String getComments();

	/**
	 * Returns the localized comments of this data entry in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized comments of this data entry
	 */
	@AutoEscape
	public String getComments(Locale locale);

	/**
	 * Returns the localized comments of this data entry in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized comments of this data entry. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getComments(Locale locale, boolean useDefault);

	/**
	 * Returns the localized comments of this data entry in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized comments of this data entry
	 */
	@AutoEscape
	public String getComments(String languageId);

	/**
	 * Returns the localized comments of this data entry in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized comments of this data entry
	 */
	@AutoEscape
	public String getComments(String languageId, boolean useDefault);

	@AutoEscape
	public String getCommentsCurrentLanguageId();

	@AutoEscape
	public String getCommentsCurrentValue();

	/**
	 * Returns a map of the locales and localized commentses of this data entry.
	 *
	 * @return the locales and localized commentses of this data entry
	 */
	public Map<Locale, String> getCommentsMap();

	/**
	 * Sets the comments of this data entry.
	 *
	 * @param comments the comments of this data entry
	 */
	public void setComments(String comments);

	/**
	 * Sets the localized comments of this data entry in the language.
	 *
	 * @param comments the localized comments of this data entry
	 * @param locale the locale of the language
	 */
	public void setComments(String comments, Locale locale);

	/**
	 * Sets the localized comments of this data entry in the language, and sets the default locale.
	 *
	 * @param comments the localized comments of this data entry
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setComments(String comments, Locale locale, Locale defaultLocale);

	public void setCommentsCurrentLanguageId(String languageId);

	/**
	 * Sets the localized commentses of this data entry from the map of locales and localized commentses.
	 *
	 * @param commentsMap the locales and localized commentses of this data entry
	 */
	public void setCommentsMap(Map<Locale, String> commentsMap);

	/**
	 * Sets the localized commentses of this data entry from the map of locales and localized commentses, and sets the default locale.
	 *
	 * @param commentsMap the locales and localized commentses of this data entry
	 * @param defaultLocale the default locale
	 */
	public void setCommentsMap(Map<Locale, String> commentsMap,
		Locale defaultLocale);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(OSPIcecap.model.DataEntry dataEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<OSPIcecap.model.DataEntry> toCacheModel();

	@Override
	public OSPIcecap.model.DataEntry toEscapedModel();

	@Override
	public OSPIcecap.model.DataEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}