/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package OSPIcecap.model;

import OSPIcecap.service.persistence.DataTypeAnalyzerLinkPK;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the DataTypeAnalyzerLink service. Represents a row in the &quot;icecap_DataTypeAnalyzerLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link OSPIcecap.model.impl.DataTypeAnalyzerLinkModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OSPIcecap.model.impl.DataTypeAnalyzerLinkImpl}.
 * </p>
 *
 * @author Jerry H. Seo
 * @see DataTypeAnalyzerLink
 * @see OSPIcecap.model.impl.DataTypeAnalyzerLinkImpl
 * @see OSPIcecap.model.impl.DataTypeAnalyzerLinkModelImpl
 * @generated
 */
@ProviderType
public interface DataTypeAnalyzerLinkModel extends BaseModel<DataTypeAnalyzerLink> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data type analyzer link model instance should use the {@link DataTypeAnalyzerLink} interface instead.
	 */

	/**
	 * Returns the primary key of this data type analyzer link.
	 *
	 * @return the primary key of this data type analyzer link
	 */
	public DataTypeAnalyzerLinkPK getPrimaryKey();

	/**
	 * Sets the primary key of this data type analyzer link.
	 *
	 * @param primaryKey the primary key of this data type analyzer link
	 */
	public void setPrimaryKey(DataTypeAnalyzerLinkPK primaryKey);

	/**
	 * Returns the link ID of this data type analyzer link.
	 *
	 * @return the link ID of this data type analyzer link
	 */
	public long getLinkId();

	/**
	 * Sets the link ID of this data type analyzer link.
	 *
	 * @param linkId the link ID of this data type analyzer link
	 */
	public void setLinkId(long linkId);

	/**
	 * Returns the type ID of this data type analyzer link.
	 *
	 * @return the type ID of this data type analyzer link
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this data type analyzer link.
	 *
	 * @param typeId the type ID of this data type analyzer link
	 */
	public void setTypeId(long typeId);

	/**
	 * Returns the analyzer ID of this data type analyzer link.
	 *
	 * @return the analyzer ID of this data type analyzer link
	 */
	public long getAnalyzerId();

	/**
	 * Sets the analyzer ID of this data type analyzer link.
	 *
	 * @param analyzerId the analyzer ID of this data type analyzer link
	 */
	public void setAnalyzerId(long analyzerId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		OSPIcecap.model.DataTypeAnalyzerLink dataTypeAnalyzerLink);

	@Override
	public int hashCode();

	@Override
	public CacheModel<OSPIcecap.model.DataTypeAnalyzerLink> toCacheModel();

	@Override
	public OSPIcecap.model.DataTypeAnalyzerLink toEscapedModel();

	@Override
	public OSPIcecap.model.DataTypeAnalyzerLink toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}