/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package OSPIcecap.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the DataCollectionLayout service. Represents a row in the &quot;icecap_DataCollectionLayout&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link OSPIcecap.model.impl.DataCollectionLayoutModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OSPIcecap.model.impl.DataCollectionLayoutImpl}.
 * </p>
 *
 * @author Jerry H. Seo
 * @see DataCollectionLayout
 * @see OSPIcecap.model.impl.DataCollectionLayoutImpl
 * @see OSPIcecap.model.impl.DataCollectionLayoutModelImpl
 * @generated
 */
@ProviderType
public interface DataCollectionLayoutModel extends BaseModel<DataCollectionLayout> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data collection layout model instance should use the {@link DataCollectionLayout} interface instead.
	 */

	/**
	 * Returns the primary key of this data collection layout.
	 *
	 * @return the primary key of this data collection layout
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this data collection layout.
	 *
	 * @param primaryKey the primary key of this data collection layout
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the collection ID of this data collection layout.
	 *
	 * @return the collection ID of this data collection layout
	 */
	public long getCollectionId();

	/**
	 * Sets the collection ID of this data collection layout.
	 *
	 * @param collectionId the collection ID of this data collection layout
	 */
	public void setCollectionId(long collectionId);

	/**
	 * Returns the layout of this data collection layout.
	 *
	 * @return the layout of this data collection layout
	 */
	@AutoEscape
	public String getLayout();

	/**
	 * Sets the layout of this data collection layout.
	 *
	 * @param layout the layout of this data collection layout
	 */
	public void setLayout(String layout);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		OSPIcecap.model.DataCollectionLayout dataCollectionLayout);

	@Override
	public int hashCode();

	@Override
	public CacheModel<OSPIcecap.model.DataCollectionLayout> toCacheModel();

	@Override
	public OSPIcecap.model.DataCollectionLayout toEscapedModel();

	@Override
	public OSPIcecap.model.DataCollectionLayout toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}