/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.osp.icebreaker.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the JobData service. Represents a row in the &quot;icebreaker_JobData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kisti.osp.icebreaker.model.impl.JobDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kisti.osp.icebreaker.model.impl.JobDataImpl}.
 * </p>
 *
 * @author Jerry H. Seo
 * @see JobData
 * @see com.kisti.osp.icebreaker.model.impl.JobDataImpl
 * @see com.kisti.osp.icebreaker.model.impl.JobDataModelImpl
 * @generated
 */
@ProviderType
public interface JobDataModel extends BaseModel<JobData> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a job data model instance should use the {@link JobData} interface instead.
	 */

	/**
	 * Returns the primary key of this job data.
	 *
	 * @return the primary key of this job data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this job data.
	 *
	 * @param primaryKey the primary key of this job data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the job ID of this job data.
	 *
	 * @return the job ID of this job data
	 */
	public long getJobId();

	/**
	 * Sets the job ID of this job data.
	 *
	 * @param jobId the job ID of this job data
	 */
	public void setJobId(long jobId);

	/**
	 * Returns the input data of this job data.
	 *
	 * @return the input data of this job data
	 */
	@AutoEscape
	public String getInputData();

	/**
	 * Sets the input data of this job data.
	 *
	 * @param inputData the input data of this job data
	 */
	public void setInputData(String inputData);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(JobData jobData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<JobData> toCacheModel();

	@Override
	public JobData toEscapedModel();

	@Override
	public JobData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}