/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.osp.icebreaker.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the OSPSchedulerEntry service. Represents a row in the &quot;icebreaker_OSPSchedulerEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.kisti.osp.icebreaker.model.impl.OSPSchedulerEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.kisti.osp.icebreaker.model.impl.OSPSchedulerEntryImpl}.
 * </p>
 *
 * @author Jerry H. Seo
 * @see OSPSchedulerEntry
 * @see com.kisti.osp.icebreaker.model.impl.OSPSchedulerEntryImpl
 * @see com.kisti.osp.icebreaker.model.impl.OSPSchedulerEntryModelImpl
 * @generated
 */
@ProviderType
public interface OSPSchedulerEntryModel extends BaseModel<OSPSchedulerEntry>,
	LocalizedModel, ShardedModel, StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a osp scheduler entry model instance should use the {@link OSPSchedulerEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this osp scheduler entry.
	 *
	 * @return the primary key of this osp scheduler entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this osp scheduler entry.
	 *
	 * @param primaryKey the primary key of this osp scheduler entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this osp scheduler entry.
	 *
	 * @return the uuid of this osp scheduler entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this osp scheduler entry.
	 *
	 * @param uuid the uuid of this osp scheduler entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the scheduler entry ID of this osp scheduler entry.
	 *
	 * @return the scheduler entry ID of this osp scheduler entry
	 */
	public long getSchedulerEntryId();

	/**
	 * Sets the scheduler entry ID of this osp scheduler entry.
	 *
	 * @param schedulerEntryId the scheduler entry ID of this osp scheduler entry
	 */
	public void setSchedulerEntryId(long schedulerEntryId);

	/**
	 * Returns the name of this osp scheduler entry.
	 *
	 * @return the name of this osp scheduler entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this osp scheduler entry.
	 *
	 * @param name the name of this osp scheduler entry
	 */
	public void setName(String name);

	/**
	 * Returns the version of this osp scheduler entry.
	 *
	 * @return the version of this osp scheduler entry
	 */
	@AutoEscape
	public String getVersion();

	/**
	 * Sets the version of this osp scheduler entry.
	 *
	 * @param version the version of this osp scheduler entry
	 */
	public void setVersion(String version);

	/**
	 * Returns the class name of this osp scheduler entry.
	 *
	 * @return the class name of this osp scheduler entry
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this osp scheduler entry.
	 *
	 * @param className the class name of this osp scheduler entry
	 */
	public void setClassName(String className);

	/**
	 * Returns the group ID of this osp scheduler entry.
	 *
	 * @return the group ID of this osp scheduler entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this osp scheduler entry.
	 *
	 * @param groupId the group ID of this osp scheduler entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this osp scheduler entry.
	 *
	 * @return the company ID of this osp scheduler entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this osp scheduler entry.
	 *
	 * @param companyId the company ID of this osp scheduler entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this osp scheduler entry.
	 *
	 * @return the user ID of this osp scheduler entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this osp scheduler entry.
	 *
	 * @param userId the user ID of this osp scheduler entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this osp scheduler entry.
	 *
	 * @return the user uuid of this osp scheduler entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this osp scheduler entry.
	 *
	 * @param userUuid the user uuid of this osp scheduler entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this osp scheduler entry.
	 *
	 * @return the create date of this osp scheduler entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this osp scheduler entry.
	 *
	 * @param createDate the create date of this osp scheduler entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this osp scheduler entry.
	 *
	 * @return the modified date of this osp scheduler entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this osp scheduler entry.
	 *
	 * @param modifiedDate the modified date of this osp scheduler entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the access method of this osp scheduler entry.
	 *
	 * @return the access method of this osp scheduler entry
	 */
	@AutoEscape
	public String getAccessMethod();

	/**
	 * Sets the access method of this osp scheduler entry.
	 *
	 * @param accessMethod the access method of this osp scheduler entry
	 */
	public void setAccessMethod(String accessMethod);

	/**
	 * Returns the authorized user of this osp scheduler entry.
	 *
	 * @return the authorized user of this osp scheduler entry
	 */
	@AutoEscape
	public String getAuthorizedUser();

	/**
	 * Sets the authorized user of this osp scheduler entry.
	 *
	 * @param authorizedUser the authorized user of this osp scheduler entry
	 */
	public void setAuthorizedUser(String authorizedUser);

	/**
	 * Returns the status of this osp scheduler entry.
	 *
	 * @return the status of this osp scheduler entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this osp scheduler entry.
	 *
	 * @param status the status of this osp scheduler entry
	 */
	public void setStatus(int status);

	/**
	 * Returns the description of this osp scheduler entry.
	 *
	 * @return the description of this osp scheduler entry
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this osp scheduler entry in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this osp scheduler entry
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this osp scheduler entry in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this osp scheduler entry. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this osp scheduler entry in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this osp scheduler entry
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this osp scheduler entry in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this osp scheduler entry
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this osp scheduler entry.
	 *
	 * @return the locales and localized descriptions of this osp scheduler entry
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this osp scheduler entry.
	 *
	 * @param description the description of this osp scheduler entry
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this osp scheduler entry in the language.
	 *
	 * @param description the localized description of this osp scheduler entry
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this osp scheduler entry in the language, and sets the default locale.
	 *
	 * @param description the localized description of this osp scheduler entry
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(String description, Locale locale,
		Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this osp scheduler entry from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this osp scheduler entry
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this osp scheduler entry from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this osp scheduler entry
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap,
		Locale defaultLocale);

	/**
	 * Returns the server ip of this osp scheduler entry.
	 *
	 * @return the server ip of this osp scheduler entry
	 */
	@AutoEscape
	public String getServerIp();

	/**
	 * Sets the server ip of this osp scheduler entry.
	 *
	 * @param serverIp the server ip of this osp scheduler entry
	 */
	public void setServerIp(String serverIp);

	/**
	 * Returns the ssh port of this osp scheduler entry.
	 *
	 * @return the ssh port of this osp scheduler entry
	 */
	@AutoEscape
	public String getSshPort();

	/**
	 * Sets the ssh port of this osp scheduler entry.
	 *
	 * @param sshPort the ssh port of this osp scheduler entry
	 */
	public void setSshPort(String sshPort);

	/**
	 * Returns the template dir of this osp scheduler entry.
	 *
	 * @return the template dir of this osp scheduler entry
	 */
	@AutoEscape
	public String getTemplateDir();

	/**
	 * Sets the template dir of this osp scheduler entry.
	 *
	 * @param templateDir the template dir of this osp scheduler entry
	 */
	public void setTemplateDir(String templateDir);

	/**
	 * Returns the template real dir of this osp scheduler entry.
	 *
	 * @return the template real dir of this osp scheduler entry
	 */
	@AutoEscape
	public String getTemplateRealDir();

	/**
	 * Sets the template real dir of this osp scheduler entry.
	 *
	 * @param templateRealDir the template real dir of this osp scheduler entry
	 */
	public void setTemplateRealDir(String templateRealDir);

	/**
	 * Returns the authorized password of this osp scheduler entry.
	 *
	 * @return the authorized password of this osp scheduler entry
	 */
	@AutoEscape
	public String getAuthorizedPassword();

	/**
	 * Sets the authorized password of this osp scheduler entry.
	 *
	 * @param authorizedPassword the authorized password of this osp scheduler entry
	 */
	public void setAuthorizedPassword(String authorizedPassword);

	/**
	 * Returns the scheduler class of this osp scheduler entry.
	 *
	 * @return the scheduler class of this osp scheduler entry
	 */
	@AutoEscape
	public String getSchedulerClass();

	/**
	 * Sets the scheduler class of this osp scheduler entry.
	 *
	 * @param schedulerClass the scheduler class of this osp scheduler entry
	 */
	public void setSchedulerClass(String schedulerClass);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

	@Override
	public Object clone();

	@Override
	public int compareTo(OSPSchedulerEntry ospSchedulerEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<OSPSchedulerEntry> toCacheModel();

	@Override
	public OSPSchedulerEntry toEscapedModel();

	@Override
	public OSPSchedulerEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}