/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.kisti.osp.spyglass.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.kisti.osp.spyglass.model.ScienceAppManager;
import com.kisti.osp.spyglass.model.ScienceAppManagerModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the ScienceAppManager service. Represents a row in the &quot;spyglass_ScienceAppManager&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link ScienceAppManagerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ScienceAppManagerImpl}.
 * </p>
 *
 * @author Jerry H. Seo
 * @see ScienceAppManagerImpl
 * @see ScienceAppManager
 * @see ScienceAppManagerModel
 * @generated
 */
@ProviderType
public class ScienceAppManagerModelImpl extends BaseModelImpl<ScienceAppManager>
	implements ScienceAppManagerModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a science app manager model instance should use the {@link ScienceAppManager} interface instead.
	 */
	public static final String TABLE_NAME = "spyglass_ScienceAppManager";
	public static final Object[][] TABLE_COLUMNS = {
			{ "scienceAppManagerId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "scienceAppId", Types.BIGINT },
			{ "managerId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("scienceAppManagerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("scienceAppId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("managerId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table spyglass_ScienceAppManager (scienceAppManagerId LONG not null primary key,userId LONG,createDate DATE null,scienceAppId LONG,managerId LONG)";
	public static final String TABLE_SQL_DROP = "drop table spyglass_ScienceAppManager";
	public static final String ORDER_BY_JPQL = " ORDER BY scienceAppManager.scienceAppManagerId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY spyglass_ScienceAppManager.scienceAppManagerId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.kisti.osp.spyglass.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.kisti.osp.spyglass.model.ScienceAppManager"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.kisti.osp.spyglass.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.kisti.osp.spyglass.model.ScienceAppManager"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.kisti.osp.spyglass.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.kisti.osp.spyglass.model.ScienceAppManager"),
			true);
	public static final long MANAGERID_COLUMN_BITMASK = 1L;
	public static final long SCIENCEAPPID_COLUMN_BITMASK = 2L;
	public static final long USERID_COLUMN_BITMASK = 4L;
	public static final long SCIENCEAPPMANAGERID_COLUMN_BITMASK = 8L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.kisti.osp.spyglass.service.util.ServiceProps.get(
				"lock.expiration.time.com.kisti.osp.spyglass.model.ScienceAppManager"));

	public ScienceAppManagerModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _scienceAppManagerId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setScienceAppManagerId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _scienceAppManagerId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ScienceAppManager.class;
	}

	@Override
	public String getModelClassName() {
		return ScienceAppManager.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("scienceAppManagerId", getScienceAppManagerId());
		attributes.put("userId", getUserId());
		attributes.put("createDate", getCreateDate());
		attributes.put("scienceAppId", getScienceAppId());
		attributes.put("managerId", getManagerId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long scienceAppManagerId = (Long)attributes.get("scienceAppManagerId");

		if (scienceAppManagerId != null) {
			setScienceAppManagerId(scienceAppManagerId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Long scienceAppId = (Long)attributes.get("scienceAppId");

		if (scienceAppId != null) {
			setScienceAppId(scienceAppId);
		}

		Long managerId = (Long)attributes.get("managerId");

		if (managerId != null) {
			setManagerId(managerId);
		}
	}

	@Override
	public long getScienceAppManagerId() {
		return _scienceAppManagerId;
	}

	@Override
	public void setScienceAppManagerId(long scienceAppManagerId) {
		_scienceAppManagerId = scienceAppManagerId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public long getScienceAppId() {
		return _scienceAppId;
	}

	@Override
	public void setScienceAppId(long scienceAppId) {
		_columnBitmask |= SCIENCEAPPID_COLUMN_BITMASK;

		if (!_setOriginalScienceAppId) {
			_setOriginalScienceAppId = true;

			_originalScienceAppId = _scienceAppId;
		}

		_scienceAppId = scienceAppId;
	}

	public long getOriginalScienceAppId() {
		return _originalScienceAppId;
	}

	@Override
	public long getManagerId() {
		return _managerId;
	}

	@Override
	public void setManagerId(long managerId) {
		_columnBitmask |= MANAGERID_COLUMN_BITMASK;

		if (!_setOriginalManagerId) {
			_setOriginalManagerId = true;

			_originalManagerId = _managerId;
		}

		_managerId = managerId;
	}

	public long getOriginalManagerId() {
		return _originalManagerId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			ScienceAppManager.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ScienceAppManager toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (ScienceAppManager)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ScienceAppManagerImpl scienceAppManagerImpl = new ScienceAppManagerImpl();

		scienceAppManagerImpl.setScienceAppManagerId(getScienceAppManagerId());
		scienceAppManagerImpl.setUserId(getUserId());
		scienceAppManagerImpl.setCreateDate(getCreateDate());
		scienceAppManagerImpl.setScienceAppId(getScienceAppId());
		scienceAppManagerImpl.setManagerId(getManagerId());

		scienceAppManagerImpl.resetOriginalValues();

		return scienceAppManagerImpl;
	}

	@Override
	public int compareTo(ScienceAppManager scienceAppManager) {
		long primaryKey = scienceAppManager.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ScienceAppManager)) {
			return false;
		}

		ScienceAppManager scienceAppManager = (ScienceAppManager)obj;

		long primaryKey = scienceAppManager.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		ScienceAppManagerModelImpl scienceAppManagerModelImpl = this;

		scienceAppManagerModelImpl._originalUserId = scienceAppManagerModelImpl._userId;

		scienceAppManagerModelImpl._setOriginalUserId = false;

		scienceAppManagerModelImpl._originalScienceAppId = scienceAppManagerModelImpl._scienceAppId;

		scienceAppManagerModelImpl._setOriginalScienceAppId = false;

		scienceAppManagerModelImpl._originalManagerId = scienceAppManagerModelImpl._managerId;

		scienceAppManagerModelImpl._setOriginalManagerId = false;

		scienceAppManagerModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ScienceAppManager> toCacheModel() {
		ScienceAppManagerCacheModel scienceAppManagerCacheModel = new ScienceAppManagerCacheModel();

		scienceAppManagerCacheModel.scienceAppManagerId = getScienceAppManagerId();

		scienceAppManagerCacheModel.userId = getUserId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			scienceAppManagerCacheModel.createDate = createDate.getTime();
		}
		else {
			scienceAppManagerCacheModel.createDate = Long.MIN_VALUE;
		}

		scienceAppManagerCacheModel.scienceAppId = getScienceAppId();

		scienceAppManagerCacheModel.managerId = getManagerId();

		return scienceAppManagerCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{scienceAppManagerId=");
		sb.append(getScienceAppManagerId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", scienceAppId=");
		sb.append(getScienceAppId());
		sb.append(", managerId=");
		sb.append(getManagerId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.kisti.osp.spyglass.model.ScienceAppManager");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>scienceAppManagerId</column-name><column-value><![CDATA[");
		sb.append(getScienceAppManagerId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>scienceAppId</column-name><column-value><![CDATA[");
		sb.append(getScienceAppId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>managerId</column-name><column-value><![CDATA[");
		sb.append(getManagerId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = ScienceAppManager.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			ScienceAppManager.class
		};
	private long _scienceAppManagerId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private Date _createDate;
	private long _scienceAppId;
	private long _originalScienceAppId;
	private boolean _setOriginalScienceAppId;
	private long _managerId;
	private long _originalManagerId;
	private boolean _setOriginalManagerId;
	private long _columnBitmask;
	private ScienceAppManager _escapedModel;
}