/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package OSPIcecap.model.impl;

import OSPIcecap.model.DataCollectionLayout;
import OSPIcecap.model.DataCollectionLayoutModel;
import OSPIcecap.model.DataCollectionLayoutSoap;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the DataCollectionLayout service. Represents a row in the &quot;icecap_DataCollectionLayout&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link DataCollectionLayoutModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DataCollectionLayoutImpl}.
 * </p>
 *
 * @author Jerry H. Seo
 * @see DataCollectionLayoutImpl
 * @see DataCollectionLayout
 * @see DataCollectionLayoutModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class DataCollectionLayoutModelImpl extends BaseModelImpl<DataCollectionLayout>
	implements DataCollectionLayoutModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a data collection layout model instance should use the {@link DataCollectionLayout} interface instead.
	 */
	public static final String TABLE_NAME = "icecap_DataCollectionLayout";
	public static final Object[][] TABLE_COLUMNS = {
			{ "collectionId", Types.BIGINT },
			{ "layout", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("collectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("layout", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table icecap_DataCollectionLayout (collectionId LONG not null primary key,layout VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table icecap_DataCollectionLayout";
	public static final String ORDER_BY_JPQL = " ORDER BY dataCollectionLayout.collectionId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY icecap_DataCollectionLayout.collectionId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(OSPIcecap.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.OSPIcecap.model.DataCollectionLayout"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(OSPIcecap.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.OSPIcecap.model.DataCollectionLayout"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DataCollectionLayout toModel(
		DataCollectionLayoutSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DataCollectionLayout model = new DataCollectionLayoutImpl();

		model.setCollectionId(soapModel.getCollectionId());
		model.setLayout(soapModel.getLayout());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DataCollectionLayout> toModels(
		DataCollectionLayoutSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<DataCollectionLayout> models = new ArrayList<DataCollectionLayout>(soapModels.length);

		for (DataCollectionLayoutSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(OSPIcecap.service.util.ServiceProps.get(
				"lock.expiration.time.OSPIcecap.model.DataCollectionLayout"));

	public DataCollectionLayoutModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _collectionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setCollectionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _collectionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DataCollectionLayout.class;
	}

	@Override
	public String getModelClassName() {
		return DataCollectionLayout.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("collectionId", getCollectionId());
		attributes.put("layout", getLayout());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long collectionId = (Long)attributes.get("collectionId");

		if (collectionId != null) {
			setCollectionId(collectionId);
		}

		String layout = (String)attributes.get("layout");

		if (layout != null) {
			setLayout(layout);
		}
	}

	@JSON
	@Override
	public long getCollectionId() {
		return _collectionId;
	}

	@Override
	public void setCollectionId(long collectionId) {
		_collectionId = collectionId;
	}

	@JSON
	@Override
	public String getLayout() {
		if (_layout == null) {
			return StringPool.BLANK;
		}
		else {
			return _layout;
		}
	}

	@Override
	public void setLayout(String layout) {
		_layout = layout;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			DataCollectionLayout.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DataCollectionLayout toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (DataCollectionLayout)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DataCollectionLayoutImpl dataCollectionLayoutImpl = new DataCollectionLayoutImpl();

		dataCollectionLayoutImpl.setCollectionId(getCollectionId());
		dataCollectionLayoutImpl.setLayout(getLayout());

		dataCollectionLayoutImpl.resetOriginalValues();

		return dataCollectionLayoutImpl;
	}

	@Override
	public int compareTo(DataCollectionLayout dataCollectionLayout) {
		long primaryKey = dataCollectionLayout.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DataCollectionLayout)) {
			return false;
		}

		DataCollectionLayout dataCollectionLayout = (DataCollectionLayout)obj;

		long primaryKey = dataCollectionLayout.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<DataCollectionLayout> toCacheModel() {
		DataCollectionLayoutCacheModel dataCollectionLayoutCacheModel = new DataCollectionLayoutCacheModel();

		dataCollectionLayoutCacheModel.collectionId = getCollectionId();

		dataCollectionLayoutCacheModel.layout = getLayout();

		String layout = dataCollectionLayoutCacheModel.layout;

		if ((layout != null) && (layout.length() == 0)) {
			dataCollectionLayoutCacheModel.layout = null;
		}

		return dataCollectionLayoutCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{collectionId=");
		sb.append(getCollectionId());
		sb.append(", layout=");
		sb.append(getLayout());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("OSPIcecap.model.DataCollectionLayout");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>collectionId</column-name><column-value><![CDATA[");
		sb.append(getCollectionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>layout</column-name><column-value><![CDATA[");
		sb.append(getLayout());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = DataCollectionLayout.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			DataCollectionLayout.class
		};
	private long _collectionId;
	private String _layout;
	private DataCollectionLayout _escapedModel;
}